//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace cOCR.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("cOCR.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon cOCRIcon {
            get {
                object obj = ResourceManager.GetObject("cOCRIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   div#description { 
        ///    margin: 2em;
        ///}
        ///div#overlay {
        ///    position: absolute;
        ///    opacity: 0
        ///}
        ///div#overlay:hover {
        ///    opacity: 1;
        ///}
        ///div#overlay .container {
        ///    position: absolute;
        ///    font-size: 1vh;
        ///    display: flex;
        ///    -webkit-justify-content: center;
        ///    justify-content: center;
        ///    -webkit-align-items: center;
        ///    align-items: center;
        ///    background-color: rgba(255, 0, 0, 0.20); 
        ///}
        ///div#json {
        ///    display: none;
        ///} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DefaultCSS {
            get {
                return ResourceManager.GetString("DefaultCSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   document.addEventListener(&quot;DOMContentLoaded&quot;, function(event) {
        ///   
        ///    var json_text = document.querySelector(&quot;#json&quot;).textContent;
        ///    var json = JSON.parse(json_text);
        ///    var annotations = json.responses[0].textAnnotations.slice(1);
        ///    
        ///    var overlay = document.createElement(&quot;div&quot;); 
        ///    overlay.id = &quot;overlay&quot;;
        ///    
        ///    function appendOverlayText(x, y, w, h, text) {
        ///        var container = document.createElement(&quot;div&quot;);
        ///        container.className = &quot;container&quot;;
        ///        container.style.le [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DefaultJS {
            get {
                return ResourceManager.GetString("DefaultJS", resourceCulture);
            }
        }
    }
}
